# Generated by Django 4.2.3 on 2023-07-16 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_colorvarient_sizevarient_alter_productimage_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.CharField(max_length=10)),
                ('is_valide', models.BooleanField(default=True)),
                ('discounted_price', models.IntegerField(default=100)),
                ('minimum_price', models.IntegerField(default=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
