# Generated by Django 4.2.3 on 2023-07-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='coupon',
            new_name='coupon_code',
        ),
    ]
